Fix/black jack clutter
yashkite/Code-Practice pull request #27
Opened 2023-11-10 13:47 UTC by bakanabaka

##What does this PR do
With this output is as desired

Fixes https://github.com/yashkite/Code-Practice/issues/15

2023-11-10 17:52 UTC, yashkite requested changes
thanks for the PR, changes requested !!!

2023-11-10 17:52 UTC, yashkite commented on Small Projects/Python/Black Jack/run.py
> +    ]
I like the old way they are presented, its more readable.
![image](https://github.com/yashkite/Code-Practice/assets/32860312/e4e22d4e-b960-471c-9e75-d875cd06cb3e)

2023-11-11 05:01 UTC, bakanabaka commented
Hey small doubt its asking something like conflicting files , how do I do that

2023-11-11 16:49 UTC, yashkite commented
@bakanabaka in your forked repository, just click on the sync fork, and update the branch
![image](https://github.com/yashkite/Code-Practice/assets/32860312/378917e2-79a9-4cdd-8ef6-cc603d480254)

2023-11-11 17:31 UTC, bakanabaka commented
Thanks for the advice man

2023-11-11 17:33 UTC, bakanabaka commented
Hey its still showing conflicting files

2023-11-12 05:21 UTC, yashkite commented
@bakanabaka because the issue related to the calculator code is already resolved. I have merged the PR and you have some code changes in the calculator which is different from the current code. that's why you are getting an error related to the conflicts. reference #25, to resolve this you can manually add this code to the current code in the repository. By doing this, I think the error will be resolved.

2023-11-12 05:31 UTC, yashkite commented
@bakanabaka  don't worry I have resolved the issue by doing the same thing I have mentioned above.

2023-11-12 05:35 UTC, yashkite requested changes
Please resolve the errors

2023-11-12 05:35 UTC, yashkite commented on Small Projects/Python/Black Jack/run.py
> +    print_stats(computer, user)
![image](https://github.com/yashkite/Code-Practice/assets/32860312/41d104ed-4dc4-4302-8650-35cbde25412d)

2023-11-16 07:48 UTC, yashkite requested changes
![image](https://github.com/yashkite/Code-Practice/assets/32860312/274a8222-38e8-4403-96d9-0792adaba764)

whenever players game over or player wins, you have to show which player have which cards and show the sum of the cards also

2023-11-19 09:54 UTC, yashkite requested changes
![image](https://github.com/yashkite/Code-Practice/assets/32860312/db33ccf9-6e4f-439a-a187-513dbbe3d86a)

the computer is showing the sum and cards directly to the user, if you don't know how this game work then you can refer [this](https://www.arkadium.com/games/blackjack/) link and play the game.

2023-12-24 10:19 UTC, closed without merging