Added module-like Python scripts which could come handy to somebody
yashkite/Code-Practice pull request #32
Opened 2023-11-20 01:26 UTC by real-zephex

**Downloads Sorter**
ℹ️ This commit adds a Python script that organizes files in the downloads folder based on their file types. The script creates folders for different file types, moving corresponding files accordingly. Additionally, it includes a function to move subfolders into a separate "Folders" folder.

**Currency Converter**
🌐 Introducing a currency converter program! This commit adds a versatile Python script designed to be used as a module. Utilizing the forex--python module, it provides exchange rate functionality. Developers can easily modify it according to specific needs.

**Weather Forecast**
🌦️ This commit introduces a Python script for retrieving weather information about a city using the OpenWeatherMap API. While designed as a module, it's adaptable for custom modifications. API key is required.

**Quotes Fetcher**
📜 Adding a Python script to fetch quotes from the zenquotes API! This script can generate random quotes, the quote of the day, or a specific number of quotes (up to 50). No API key required, making it easy to integrate.

🚀 Ready for merge!

2023-11-21 10:46 UTC, real-zephex commented
*Added currency.md

2023-11-21 18:03 UTC, yashkite requested changes
some changes are requested

2023-11-22 10:46 UTC, real-zephex reviewed
since we have declared it a class method, it is bound to the class instead of class instance. The first parameter refers to the class itself.

2023-11-22 10:47 UTC, real-zephex commented on Small Projects/Python/Quotes/quote.py
doing it rn

2023-11-22 10:55 UTC, real-zephex commented on Small Projects/Python/Quotes/quote.py
done

2023-11-22 10:55 UTC, real-zephex commented
@yashkite 
I made the required changes, please review them!

2023-11-22 17:31 UTC, yashkite approved these changes
Thanks for the PR.

2023-11-22 17:31 UTC, merged